package com.esd.vs.model;

import java.util.Date;

public class Sms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.id
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.ip
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.phone
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.code
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.account_sid
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String accountSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.account_token
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String accountToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.appId
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.result
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.status_code
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.create_time
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.create_method
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String createMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.update_time
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.update_method
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    private String updateMethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.id
     *
     * @return the value of sms.id
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.id
     *
     * @param id the value for sms.id
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.ip
     *
     * @return the value of sms.ip
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.ip
     *
     * @param ip the value for sms.ip
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.phone
     *
     * @return the value of sms.phone
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.phone
     *
     * @param phone the value for sms.phone
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.code
     *
     * @return the value of sms.code
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.code
     *
     * @param code the value for sms.code
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.account_sid
     *
     * @return the value of sms.account_sid
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getAccountSid() {
        return accountSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.account_sid
     *
     * @param accountSid the value for sms.account_sid
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setAccountSid(String accountSid) {
        this.accountSid = accountSid == null ? null : accountSid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.account_token
     *
     * @return the value of sms.account_token
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getAccountToken() {
        return accountToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.account_token
     *
     * @param accountToken the value for sms.account_token
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setAccountToken(String accountToken) {
        this.accountToken = accountToken == null ? null : accountToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.appId
     *
     * @return the value of sms.appId
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.appId
     *
     * @param appid the value for sms.appId
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.result
     *
     * @return the value of sms.result
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.result
     *
     * @param result the value for sms.result
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.status_code
     *
     * @return the value of sms.status_code
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.status_code
     *
     * @param statusCode the value for sms.status_code
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.create_time
     *
     * @return the value of sms.create_time
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.create_time
     *
     * @param createTime the value for sms.create_time
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.create_method
     *
     * @return the value of sms.create_method
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getCreateMethod() {
        return createMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.create_method
     *
     * @param createMethod the value for sms.create_method
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setCreateMethod(String createMethod) {
        this.createMethod = createMethod == null ? null : createMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.update_time
     *
     * @return the value of sms.update_time
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.update_time
     *
     * @param updateTime the value for sms.update_time
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.update_method
     *
     * @return the value of sms.update_method
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public String getUpdateMethod() {
        return updateMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.update_method
     *
     * @param updateMethod the value for sms.update_method
     *
     * @mbggenerated Mon Sep 01 16:51:30 CST 2014
     */
    public void setUpdateMethod(String updateMethod) {
        this.updateMethod = updateMethod == null ? null : updateMethod.trim();
    }
}